FROM node:22 AS build

WORKDIR /app
COPY ../ .
RUN npm i

RUN npm run build

FROM node:22
LABEL org.opencontainers.image.source=https://github.com/b-turchyn/lifetracker
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm i

COPY --from=build /app/dist/ /app/

CMD [ "worker.js" ]

